name: darc
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  fpdart: ^1.2.0
  fresh_dio: ^0.4.4
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0

